name: Debug Digger Workflow

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  debug_job:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: fundaztic
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.11'

      - name: Install OCI CLI
        run: |
          bash -c "$(curl -L https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh)" -- --accept-all-defaults
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Create OCI config directory
        run: mkdir -p ~/.oci

      - name: Save OCI private key
        run: |
            echo "${{ secrets.OCI_PRIVATE_KEY }}" > ~/.oci/oci_api_key.pem

      - name: Write OCI config file
        run: |
          echo "[DEFAULT]" > ~/.oci/config
          echo "user=${{ secrets.OCI_USER_OCID }}" >> ~/.oci/config
          echo "fingerprint=${{ secrets.OCI_FINGERPRINT }}" >> ~/.oci/config
          echo "key_file=/home/runner/.oci/oci_api_key.pem" >> ~/.oci/config
          echo "tenancy=${{ secrets.OCI_TENANCY }}" >> ~/.oci/config
          echo "region=ap-singapore-1" >> ~/.oci/config
        shell: bash

      - name: Test OCI Authentication
        run: |
          oci iam compartment list --compartment-id ocid1.tenancy.oc1..aaaaaaaa4gsdatqr4iu26stu45vhvtdy3qtzzapaeztf2wazln2qhxlvfwjq
