name: Debug Digger Workflow

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  debug_job:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: fundaztic
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.11'

      - name: Install OCI CLI
        run: |
          bash -c "$(curl -L https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh)" -- --accept-all-defaults
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Verify OCI CLI
        run: oci --version

      - name: Test OCI Authentication
        run: |
          oci iam compartment list --all
