name: Debug Digger Workflow

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  debug_job:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: fundaztic
    steps:
      - uses: actions/checkout@v4
      
      - run: pwd
      - run: ls -la
