name: Debug Digger Workflow

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  debug_job:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: fundaztic
    steps:
      - uses: actions/checkout@v4

      - name: Install OCI CLI
        run: |
          curl -L https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh | bash -s -- --accept-all-defaults --no-sudo
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Verify OCI CLI
        run: oci --version

      - name: Test OCI Authentication
        run: |
          oci iam compartment list --all
